CREATE PROCEDURE ConsultarProductoTransacciones(
	@IdProducto INT, 
	@IdEmpresa VARCHAR(36)
)
AS
BEGIN
	
	SELECT 
		ID_TRANSACCION,FECHA,TRANSACCIONES.ID_PRODUCTO,CANTIDAD,TRANSACCIONES.ID_TIPOTRANSACCION,
		ID_EMPLEADOCLIENTE, TRANSACCIONES.FECHA_REGISTRO, TRANSACCIONES.FECHA_MODIFICACION, 
		RTRIM(TIPO_TRANSACCION.NOMBRE) AS NOMBRE_TIPO_TRANSACCION, RTRIM(PRODUCTOS.NOMBRE) AS NOMBRE_PRODUCTO	
	FROM TRANSACCIONES 
	INNER JOIN PRODUCTOS
	ON TRANSACCIONES.ID_PRODUCTO = PRODUCTOS.ID_PRODUCTO
	INNER JOIN TIPO_TRANSACCION 
	ON TRANSACCIONES.ID_TIPOTRANSACCION = TIPO_TRANSACCION.ID_TIPOTRANSACCION
	WHERE PRODUCTOS.ID_PRODUCTO = @IdProducto AND PRODUCTOS.ID_EMPRESA = @IdEmpresa
	ORDER BY FECHA DESC

END

GO