CREATE PROCEDURE [dbo].[ConsultarEmpleadoPrestamos](
	@IdEmpresa VARCHAR(36),
	@IdEmpleado INT
)
AS
BEGIN

	SELECT
		ID_GASTO, 
		RTRIM(TIPO_GASTO) AS TIPO_GASTO, 
		RTRIM(DESCRIPCION) AS DESCRIPCION,
		VALOR,
		FECHA,
		ESTADO,
		ID_EMPLEADO,
		FECHA_REGISTRO,
		FECHA_MODIFICACION,
		ID_EMPRESA
	FROM GASTOS
	WHERE ID_EMPRESA = @IdEmpresa 
	AND ID_EMPLEADO = @IdEmpleado 
	AND ESTADO = 'ASIGNADO' 
	AND TIPO_GASTO = 'PRESTAMOS'

END

GO