CREATE PROCEDURE ConsultarCajaMenor(@IdEmpresa VARCHAR(36))
 AS
  BEGIN

	SELECT TOP 1 
        ID_REGISTRO,ANIO,MES,CONVERT(nvarchar(10),DIA,23) AS DIA, QUINCENA, SALDO_INICIAL, 
		ACUMULADO, FECHA_REGISTRO, FECHA_MODIFICACION, CAST(ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA	    
	FROM CAJA_MENOR 
    WHERE ID_EMPRESA  = @IdEmpresa
	ORDER BY FECHA_MODIFICACION DESC

 END

 GO

 