CREATE PROCEDURE [dbo].[ConsultarEmpleadoInsumos](
	@IdEmpleado INT,
	@IdEmpresa VARCHAR(36)
)
AS
BEGIN

	SELECT 
		ID_TRANSACCION, FECHA, TRANSACCIONES.FECHA_REGISTRO,
		ID_TIPOTRANSACCION, CANTIDAD, TRANSACCIONES.ID_PRODUCTO,
		ID_EMPLEADO, RTRIM(PRODUCTOS.NOMBRE) AS NOMBRE_PRODUCTO,
		CAST(TRANSACCIONES.ID_EMPRESA AS VARCHAR(36)) ID_EMPRESA
	FROM TRANSACCIONES 
	INNER JOIN PRODUCTOS 
	ON PRODUCTOS.ID_PRODUCTO = TRANSACCIONES.ID_PRODUCTO 
	WHERE TRANSACCIONES.ID_EMPLEADO = @IdEmpleado
	AND TRANSACCIONES.ID_EMPRESA = @IdEmpresa
	ORDER BY PRODUCTOS.NOMBRE ASC

END

GO