CREATE PROCEDURE ConsultarSistemaPropiedades
AS
BEGIN
	
	SELECT 
		CAST(ID_SISTEMA_PROPIEDAD AS VARCHAR(36)) AS ID_SISTEMA_PROPIEDAD, 
		RTRIM(DESCRIPCION) AS DESCRIPCION,RTRIM(CODIGO) AS CODIGO, RTRIM(TIPO) AS TIPO
	FROM SISTEMA_PROPIEDADES
	ORDER BY DESCRIPCION ASC

END

GO
