CREATE PROCEDURE [dbo].[ConsultarServiciosAdmin]
AS
BEGIN	
	SELECT
		ID_SERVICIO,
		RTRIM(SERVICIOS.NOMBRE) AS NOMBRE,
		RTRIM(SERVICIOS.DESCRIPCION) AS DESCRIPCION,
		SERVICIOS.ID_TIPOSERVICIO,
		RTRIM(SERVICIOS.ID_CATEGORIA_SERVICIO) AS ID_CATEGORIA_SERVICIO,
		SERVICIOS.FECHA_REGISTRO,
		SERVICIOS.FECHA_MODIFICACION,
		TIPO_SERVICIO.NOMBRE AS NOMBRE_TIPO_SERVICIO,
		CATEGORIA_SERVICIOS.NOMBRE AS NOMBRE_CATEGORIA_SERVICIO
	FROM SERVICIOS
	INNER JOIN TIPO_SERVICIO
	ON SERVICIOS.ID_TIPOSERVICIO = TIPO_SERVICIO.ID_TIPOSERVICIO
	INNER JOIN CATEGORIA_SERVICIOS
	ON SERVICIOS.ID_CATEGORIA_SERVICIO = CATEGORIA_SERVICIOS.ID_CATEGORIA_SERVICIO
	ORDER BY SERVICIOS.NOMBRE
END

GO