CREATE PROCEDURE ConsultarCategoriaServicios
AS
BEGIN

	SELECT CAST((ID_CATEGORIA_SERVICIO) AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO,
	UPPER(RTRIM(NOMBRE)) AS NOMBRE,
	RTRIM(DESCRIPCION) AS DESCRIPCION
	FROM CATEGORIA_SERVICIOS

END
GO