CREATE PROCEDURE [dbo].[ConsultarClientes](
	@IdEmpresa VARCHAR(36)
)
AS
BEGIN

	SET NOCOUNT ON;

	SELECT 
		ID_CLIENTE,
		RTRIM(CEDULA) AS CEDULA,
		RTRIM(NOMBRES) AS NOMBRES,
		RTRIM(APELLIDOS) AS APELLIDOS,
		RTRIM(TELEFONO_FIJO) AS TELEFONO_FIJO,
		RTRIM(TELEFONO_MOVIL) AS TELEFONO_MOVIL,
		RTRIM(MAIL) AS MAIL,
		RTRIM(DIRECCION) AS DIRECCION,
		CLIENTES.ID_BARRIO,
		FECHA_NACIMIENTO,
		BARRIOS.NOMBRE AS BARRIO,
		CLIENTES.ID_TIPO,RTRIM(ESTADO) AS ESTADO,
		FECHA_REGISTRO,
		USUARIO_REGISTRO,
		FECHA_MODIFICACION,
		USUARIO_MODIFICACION,
		CAST(ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,
		BARRIOS.ID_MUNICIPIO AS ID_MUNICIPIO,
		RTRIM(MUNICIPIOS.ID_DEPARTAMENTO) AS ID_DEPARTAMENTO,
		RTRIM(TIPO_CLIENTE.NOMBRE) AS TIPO_CLIENTE
	FROM CLIENTES INNER JOIN BARRIOS 
	ON CLIENTES.ID_BARRIO = BARRIOS.ID_BARRIO
	INNER JOIN MUNICIPIOS 
	ON MUNICIPIOS.ID_MUNICIPIO = BARRIOS.ID_MUNICIPIO
	INNER JOIN TIPO_CLIENTE 
	ON TIPO_CLIENTE.ID_TIPO = CLIENTES.ID_TIPO
	WHERE ID_EMPRESA = @IdEmpresa
	ORDER BY ID_CLIENTE ASC

END

GO