CREATE PROCEDURE ConsultarEmpleados(
	@IdEmpresa VARCHAR(36)
)
AS
BEGIN

	SELECT 
		ID_EMPLEADO,
		RTRIM(CEDULA) AS CEDULA, 
		CAST(ID_TIPOPAGO AS VARCHAR(36)) AS ID_TIPOPAGO, 
		MONTO, 
		RTRIM(NOMBRES) AS NOMBRES,
		RTRIM(APELLIDOS) AS APELLIDOS,
		RTRIM(TELEFONO_FIJO) AS TELEFONO_FIJO,
		RTRIM(TELEFONO_MOVIL) AS TELEFONO_MOVIL,
		RTRIM(DIRECCION) AS DIRECCION,
		EMPLEADOS.ID_BARRIO,
		FECHA_NACIMIENTO,
		RTRIM(ESTADO_CIVIL) AS ESTADO_CIVIL,
		NUMERO_HIJOS,RTRIM(ESTADO) AS ESTADO,
		BARRIOS.NOMBRE AS BARRIO,
		FECHA_REGISTRO,
		FECHA_MODIFICACION,
		CAST(ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,
		BARRIOS.ID_MUNICIPIO AS ID_MUNICIPIO
	FROM EMPLEADOS 
	INNER JOIN BARRIOS 
	ON EMPLEADOS.ID_BARRIO = BARRIOS.ID_BARRIO	
	WHERE ID_EMPRESA = @IdEmpresa
	ORDER BY ID_EMPLEADO ASC

END

GO