CREATE PROCEDURE ConsultarTipoServicios
AS
BEGIN

	SELECT 
		ID_TIPOSERVICIO,
		RTRIM(NOMBRE) AS NOMBRE,
		RTRIM(DESCRIPCION) AS DESCRIPCION,
		FECHA_REGISTRO,
		FECHA_MODIFICACION,
		RTRIM(ID_CATEGORIA_SERVICIO) AS ID_CATEGORIA_SERVICIO
	FROM TIPO_SERVICIO ORDER BY NOMBRE ASC

END

GO