CREATE PROCEDURE ConsultarCliente(
	@CedulaCliente VARCHAR(15), 
	@IdEmpresa VARCHAR(36)
)
AS
BEGIN

	SELECT 
		ID_CLIENTE,
		RTRIM(CEDULA) AS CEDULA,
		RTRIM(NOMBRES) AS NOMBRES,
		RTRIM(APELLIDOS) AS APELLIDOS,
		RTRIM(TELEFONO_FIJO) AS TELEFONO_FIJO,
		RTRIM(TELEFONO_MOVIL) AS TELEFONO_MOVIL,
		RTRIM(MAIL) AS MAIL,
		RTRIM(DIRECCION) AS DIRECCION,
		CLIENTES.ID_BARRIO,
		FECHA_NACIMIENTO,
		BARRIOS.NOMBRE AS BARRIO,
		ID_TIPO,RTRIM(ESTADO) AS ESTADO,
		FECHA_REGISTRO,
		FECHA_MODIFICACION,
		CAST(ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,
		ID_USUARIO_CREACION,
		BARRIOS.ID_MUNICIPIO AS ID_MUNICIPIO,
		RTRIM(MUNICIPIOS.ID_DEPARTAMENTO) AS ID_DEPARTAMENTO
	FROM CLIENTES 
	INNER JOIN BARRIOS 
	ON CLIENTES.ID_BARRIO = BARRIOS.ID_BARRIO
	INNER JOIN MUNICIPIOS
	ON BARRIOS.ID_MUNICIPIO = MUNICIPIOS.ID_MUNICIPIO
	WHERE ID_EMPRESA = @IdEmpresa 
	AND CEDULA = @CedulaCliente

END

GO