CREATE PROCEDURE ConsultarEmpresaPropiedades(@IdEmpresa VARCHAR(36))
AS
BEGIN
	
	SELECT 
		RTRIM(ID_EMPRESA_PROPIEDAD) as ID_EMPRESA_PROPIEDAD,
		RTRIM(ID_EMPRESA) AS ID_EMPRESA,
		RTRIM(ID_SISTEMA_PROPIEDAD) AS ID_SISTEMA_PROPIEDAD,
		RTRIM(VALOR_PROPIEDAD) AS VALOR_PROPIEDAD,
		(SELECT RTRIM(CODIGO) FROM SISTEMAS_PROPIEDADES WHERE ID_SISTEMA_PROPIEDAD = EMPRESA_PROPIEDADES.ID_SISTEMA_PROPIEDAD) AS CODIGO
	FROM EMPRESA_PROPIEDADES 
	WHERE ID_EMPRESA = @IdEmpresa

END

GO