CREATE PROCEDURE [dbo].[ConsultarSedesPrincipales]
AS
BEGIN

	SELECT 
		CAST((ID_EMPRESA) AS VARCHAR(36)) AS ID_EMPRESA,
		UPPER(RTRIM(NOMBRE)) AS NOMBRE,
		RTRIM(DESCRIPCION) AS DESCRIPCION,
		RTRIM(DIRECCION) AS DIRECCION,
		RTRIM(TELEFONO_FIJO) AS TELEFONO_FIJO,
		RTRIM(TELEFONO_MOVIL) AS TELEFONO_MOVIL,
		RTRIM(MAIL) AS MAIL,
		RTRIM(LOGO) AS LOGO,
		CAST((ID_SEDEPRINCIPAL) AS VARCHAR(36)) AS ID_SEDEPRINCIPAL,
		CAST((ID_CATEGORIA_SERVICIO) AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO,
		RTRIM(ESTADO) AS ESTADO
	FROM EMPRESA
	WHERE ID_SEDEPRINCIPAL IS NULL

END

GO




