CREATE PROCEDURE ConsultarEmpresas
AS 
BEGIN

	SELECT 
		CAST(ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA, RTRIM(NOMBRE) AS NOMBRE, RTRIM(DESCRIPCION) AS DESCRIPCION, 
		RTRIM(DIRECCION) AS DIRECCION, TELEFONO_FIJO, TELEFONO_MOVIL, RTRIM(MAIL) AS MAIL, RTRIM(LOGO) AS LOGO, 
		ISNULL(ID_SEDEPRINCIPAL, '00000000-0000-0000-0000-000000000000') AS ID_SEDEPRINCIPAL,
		CAST(ID_CATEGORIA_SERVICIO AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO
	FROM EMPRESA
	ORDER BY NOMBRE ASC

END

GO