CREATE PROCEDURE [dbo].[ConsultarEmpleadoInsumos](
	@IdEmpleado VARCHAR(36)
)
AS
BEGIN

	SELECT 
		ID_TRANSACCION, FECHA, TRANSACCIONES.FECHA_REGISTRO,
		ID_TIPOTRANSACCION, CANTIDAD, TRANSACCIONES.ID_PRODUCTO,
		ID_EMPLEADO AS ID_EMPLEADOCLIENTE,
		RTRIM(PRODUCTOS.NOMBRE) AS NOMBRE_PRODUCTO	
	FROM TRANSACCIONES 
	INNER JOIN PRODUCTOS 
	ON PRODUCTOS.ID_PRODUCTO = TRANSACCIONES.ID_PRODUCTO 
	WHERE ID_EMPLEADO = @IdEmpleado 
	ORDER BY PRODUCTOS.NOMBRE ASC

END

GO