CREATE PROCEDURE ConsultarTodasLasEmpresas
AS
BEGIN

	SELECT 
		CAST((E.ID_EMPRESA) AS VARCHAR(36)) AS ID_EMPRESA,
		UPPER(RTRIM(E.NOMBRE)) AS NOMBRE,
		RTRIM(E.DESCRIPCION) AS DESCRIPCION,
		RTRIM(E.DIRECCION) AS DIRECCION,
		RTRIM(E.TELEFONO_FIJO) AS TELEFONO_FIJO,
		RTRIM(E.TELEFONO_MOVIL) AS TELEFONO_MOVIL,
		RTRIM(E.MAIL) AS MAIL,
		RTRIM(E.LOGO) AS LOGO,
		CAST((E.ID_SEDEPRINCIPAL) AS VARCHAR(36)) AS ID_SEDEPRINCIPAL,
		CAST((E.ID_CATEGORIA_SERVICIO) AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO,
		RTRIM(E.ESTADO) AS ESTADO,
		UPPER(RTRIM(S.NOMBRE)) AS NOMBRE_SEDEPRINCIPAL		
	FROM EMPRESA E
	LEFT JOIN EMPRESA S ON E.ID_SEDEPRINCIPAL = S.ID_EMPRESA

END

GO