CREATE PROCEDURE [dbo].[ConsultarBarriosAdmin]
AS
BEGIN

	SELECT 
		ID_BARRIO,
		RTRIM(BARRIOS.NOMBRE) AS NOMBRE,
		BARRIOS.ID_MUNICIPIO AS ID_MUNICIPIO,
		CODIGO,
		ID_OBJECT,
		RTRIM(MUNICIPIOS.NOMBRE) AS NOMBRE_MUNICIPIO,
		RTRIM(MUNICIPIOS.ID_DEPARTAMENTO) AS ID_DEPARTAMENTO
	FROM BARRIOS
	INNER JOIN MUNICIPIOS
	ON BARRIOS.ID_MUNICIPIO = MUNICIPIOS.ID_MUNICIPIO	
	ORDER BY NOMBRE		

END

GO
