CREATE PROCEDURE ConsultarMenuAdmin
AS
BEGIN

	SELECT ID_MENU, RTRIM(RUTA_ACCESO) AS RUTA_ACCESO, RTRIM(DESCRIPCION) AS DESCRIPCION,	
	LOGO_BASE64, _PARENTID, _LEVEL, _CHILDREN
	FROM MENU
	ORDER BY DESCRIPCION

END

GO

