CREATE PROCEDURE EliminarServicioPromocion(
	@IdDetallePromocion UNIQUEIDENTIFIER,
	@IdPromocion UNIQUEIDENTIFIER
)
AS
BEGIN

	IF((SELECT COUNT(ID_DETALLE_PROMOCION) FROM DETALLE_PROMOCIONES WHERE ID_PROMOCION = @IdPromocion) = 1) BEGIN
		DELETE FROM DETALLE_PROMOCIONES WHERE ID_DETALLE_PROMOCION = @IdDetallePromocion
		DELETE FROM PROMOCIONES WHERE ID_PROMOCION = @IdPromocion
	END
	ELSE BEGIN
		DELETE FROM DETALLE_PROMOCIONES WHERE ID_DETALLE_PROMOCION = @IdDetallePromocion
	END	

END

GO