CREATE PROCEDURE ValidarUsuario(@Nombre VARCHAR(25), @Password VARCHAR(100), @ValidarIntegracion BIT = NULL, @CodigoIntegracion VARCHAR(36) = NULL)
AS
BEGIN	
	
	IF @ValidarIntegracion = 1 AND ISNULL(@CodigoIntegracion,'') <> '' BEGIN

		UPDATE 
			USUARIOS SET VERIFICADO = 1 
		WHERE NOMBRE = @Nombre AND CONTRASENIA = @Password
		AND CODIGO_INTEGRACION = @CodigoIntegracion
		AND VERIFICADO IS NULL
		
		SELECT 
			ID_USUARIO,RTRIM(USUARIOS.NOMBRE) AS NOMBRE,RTRIM(CONTRASENIA) AS CONTRASENIA,RTRIM(PERFIL) AS PERFIL,
			CAST(USUARIOS.ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,RTRIM(CODIGO_INTEGRACION) AS CODIGO_INTEGRACION,
			VERIFICADO,FECHA_REGISTRO,FECHA_MODIFICACION,EMPRESA.NOMBRE AS NOMBRE_EMPRESA, 
			CAST(EMPRESA.ID_CATEGORIA_SERVICIO AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO
		FROM USUARIOS 
		INNER JOIN EMPRESA 
		ON EMPRESA.ID_EMPRESA = USUARIOS.ID_EMPRESA
		WHERE USUARIOS.NOMBRE = @Nombre AND CONTRASENIA = @Password
		AND CODIGO_INTEGRACION = @CodigoIntegracion

	END
	ELSE BEGIN

		DECLARE @IdEmpresa UNIQUEIDENTIFIER
		DECLARE @HashKey VARCHAR(34)
		SET @IdEmpresa = (SELECT TOP 1 ID_EMPRESA FROM USUARIOS WHERE NOMBRE = @Nombre AND CONTRASENIA = @Password)

		IF @IdEmpresa IS NOT NULL BEGIN
			SET @HashKey = CONVERT(VARCHAR(34),HASHBYTES('MD5',CONCAT(@Nombre,@IdEmpresa)),2)
		END

		SELECT 
			ID_USUARIO,RTRIM(USUARIOS.NOMBRE) AS NOMBRE,RTRIM(CONTRASENIA) AS CONTRASENIA,RTRIM(PERFIL) AS PERFIL,
			CAST(USUARIOS.ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,CODIGO_INTEGRACION,FECHA_REGISTRO,FECHA_MODIFICACION,
			VERIFICADO,@HashKey AS HashKey,ISNULL(USUARIOS.MAIL,RTRIM(EMPRESA.MAIL)) AS MAIL,EMPRESA.NOMBRE AS NOMBRE_EMPRESA, 
			CAST(EMPRESA.ID_CATEGORIA_SERVICIO AS VARCHAR(36)) AS ID_CATEGORIA_SERVICIO
		FROM USUARIOS 
		INNER JOIN EMPRESA 
		ON USUARIOS.ID_EMPRESA = EMPRESA.ID_EMPRESA 
		WHERE USUARIOS.NOMBRE = @Nombre 
		AND CONTRASENIA = @Password

	END

END

GO