CREATE PROCEDURE ValidarUsuario(@Nombre VARCHAR(25), @Password CHAR(15), @ValidarIntegracion BIT = NULL, @CodigoIntegracion VARCHAR(26) = NULL)
AS
BEGIN	
	
	IF @ValidarIntegracion = 1 AND ISNULL(@CodigoIntegracion,'') <> '' BEGIN
		
		SELECT ID_USUARIO,RTRIM(USUARIOS.NOMBRE) AS NOMBRE,RTRIM(CONTRASEÑA) AS CONTRASEÑA,RTRIM(PERFIL) AS PERFIL,
		CAST(USUARIOS.ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,RTRIM(CODIGO_INTEGRACION) AS CODIGO_INTEGRACION,
		FECHA_REGISTRO,FECHA_MODIFICACION,EMPRESA.NOMBRE AS NOMBRE_EMPRESA FROM USUARIOS INNER JOIN EMPRESA 
		ON EMPRESA.ID_EMPRESA = USUARIOS.ID_EMPRESA WHERE USUARIOS.NOMBRE = @Nombre AND CONTRASEÑA = @Password
		AND CODIGO_INTEGRACION = @CodigoIntegracion

	END
	ELSE BEGIN

		DECLARE @IdEmpresa UNIQUEIDENTIFIER
		DECLARE @HashKey VARCHAR(34)
		SET @IdEmpresa = (SELECT TOP 1 ID_EMPRESA FROM USUARIOS WHERE NOMBRE = @Nombre AND CONTRASEÑA = @Password)

		IF @IdEmpresa IS NOT NULL BEGIN
			SET @HashKey = CONVERT(VARCHAR(34),HASHBYTES('MD5',CONCAT(@Nombre,@IdEmpresa)),2)
		END

		SELECT ID_USUARIO,RTRIM(USUARIOS.NOMBRE) AS NOMBRE,RTRIM(CONTRASEÑA) AS CONTRASEÑA,RTRIM(PERFIL) AS PERFIL,
		CAST(USUARIOS.ID_EMPRESA AS VARCHAR(36)) AS ID_EMPRESA,CODIGO_INTEGRACION,FECHA_REGISTRO,FECHA_MODIFICACION,
		@HashKey AS HashKey,RTRIM(EMPRESA.MAIL) AS MAIL,EMPRESA.NOMBRE AS NOMBRE_EMPRESA FROM USUARIOS 
		INNER JOIN EMPRESA ON USUARIOS.ID_EMPRESA = EMPRESA.ID_EMPRESA WHERE USUARIOS.NOMBRE = @Nombre 
		AND CONTRASEÑA = @Password

	END

END

GO


