CREATE PROCEDURE ValidarUsuarioAdmin(@Nombre VARCHAR(25), @Password CHAR(30))
AS
BEGIN	

		DECLARE @HashKey VARCHAR(36)
		SET @HashKey = '00000000-0000-0000-0000-000000000000'

		SELECT 
			ID_USUARIO,RTRIM(NOMBRE) AS NOMBRE,RTRIM(CONTRASEÑA) AS CONTRASEÑA,'ADMINISTRADOR' AS PERFIL,
			@HashKey AS ID_EMPRESA,@HashKey AS CODIGO_INTEGRACION,FECHA_REGISTRO,FECHA_MODIFICACION,
			@HashKey AS HashKey, MAIL,'[MULTIPLE]' AS NOMBRE_EMPRESA 
		FROM ADMINISTRADORES 
		WHERE NOMBRE = @Nombre AND CONTRASEÑA = @Password

END

GO