CREATE TABLE [dbo].[ACUMULADOS_CAJA] (
    [ID_REGISTRO]           UNIQUEIDENTIFIER NOT NULL,
    [ID_CAJA_MENOR]         INT				 NOT NULL,
    [VALOR]					DECIMAL (18,2)   NOT NULL,
    [FECHA_REGISTRO]        DATETIME         NULL,
    [USUARIO_REGISTRO]      CHAR (25)        NULL,
    [FECHA_MODIFICACION]    DATETIME         NULL,
    [USUARIO_MODIFICACION]  CHAR (25)        NULL,    
    [ID_EMPRESA]            UNIQUEIDENTIFIER NOT NULL    
    CONSTRAINT [FK_ID_EMPRESA_ACUMULADOS_CAJA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA])    
);

GO