CREATE TABLE [dbo].[AGENDA] (
    [ID_AGENDA]          INT       IDENTITY (1, 1) NOT NULL,
    [FECHA_INICIO]       DATETIME  NULL,
    [FECHA_FIN]          DATETIME  NULL,
    [ID_CLIENTE]         CHAR (15) NULL,
    [SERVICIO]           INT       NULL,
    [ID_EMPLEADO]        CHAR (15) NULL,
    [ESTADO]             CHAR (12) NULL,
    [FECHA_REGISTRO]     DATETIME  NULL,
    [FECHA_MODIFICACION] DATETIME  NULL,
    CONSTRAINT [PK_AGENDA] PRIMARY KEY CLUSTERED ([ID_AGENDA] ASC),
    CONSTRAINT [FK_SERVICIO] FOREIGN KEY ([SERVICIO]) REFERENCES [dbo].[SERVICIOS] ([ID_SERVICIO])
);


GO

--Create insert trigger
CREATE TRIGGER [dbo].[MA_MasterCreation] ON [dbo].[AGENDA] FOR INSERT
AS
UPDATE [AGENDA]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [AGENDA].ID_AGENDA = (SELECT TOP 1 ID_AGENDA FROM INSERTED)


GO

--Create update trigger
CREATE TRIGGER [dbo].[MA_MasterModification] ON [dbo].[AGENDA] FOR UPDATE
AS
UPDATE [AGENDA]
SET FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [AGENDA].ID_AGENDA = (SELECT TOP 1 ID_AGENDA FROM INSERTED)

