CREATE TABLE [dbo].[BARRIOS] (
    [ID_BARRIO]    INT       IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       CHAR (30) NULL,
    [ID_MUNICIPIO] INT       NOT NULL,
    [CODIGO]       VARCHAR(10) NULL 
    CONSTRAINT [PK_BARRIOS] PRIMARY KEY CLUSTERED ([ID_BARRIO] ASC),
    CONSTRAINT [FK_MUNICIPIO] FOREIGN KEY ([ID_MUNICIPIO]) REFERENCES [dbo].[MUNICIPIOS] ([ID_MUNICIPIO])
);

