CREATE TABLE [dbo].[CAJA_MENOR] (
    [ID_REGISTRO]        INT              IDENTITY (1, 1) NOT NULL,
    [AÑO]                INT              NULL,
    [MES]                INT              NULL,
    [DIA]                SMALLDATETIME    NULL,
    [QUINCENA]           INT              NULL,
    [SALDO_INICIAL]      REAL             CONSTRAINT [DF_CAJA_MENOR_SALDO_INICIAL] DEFAULT ((0)) NOT NULL,
    [ACUMULADO]          REAL             CONSTRAINT [DF_CAJA_MENOR_ACUMULADO] DEFAULT ((0)) NULL,
    [ID_EMPRESA]         UNIQUEIDENTIFIER NOT NULL,
    [FECHA_REGISTRO]     DATETIME         NULL,
    [FECHA_MODIFICACION] DATETIME         NULL,
    CONSTRAINT [PK_CAJA_MENOR_1] PRIMARY KEY CLUSTERED ([ID_REGISTRO] ASC),
    CONSTRAINT [FK_ID_EMPRESA_CAJA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA])
);

GO

