CREATE TABLE [dbo].[CALIFICACION_SERVICIO] (
    [ID_CALIFICACION_SERVICIO] INT       IDENTITY (1, 1) NOT NULL,
    [ID_EMPLEADO_SERVICIO]     INT       NULL,
    [CALIFICACION_SERVICIO]    CHAR (10) NULL,
    [CALIFICACION_ACTITUDINAL] CHAR (10) NULL,
    [FECHA]                    DATETIME  NULL,
    CONSTRAINT [PK_CALIFICACION_SERVICIO] PRIMARY KEY CLUSTERED ([ID_CALIFICACION_SERVICIO] ASC),
    CONSTRAINT [FK_ID_EMPLEADO_SERVICIO] FOREIGN KEY ([ID_EMPLEADO_SERVICIO]) REFERENCES [dbo].[EMPLEADOS_SERVICIOS] ([ID_EMPLEADO_SERVICIO])
);

