CREATE TABLE [dbo].[CATEGORIA_SERVICIOS] (
    [ID_CATEGORIA_SERVICIO]			UNIQUEIDENTIFIER NOT NULL,    
    [NOMBRE]         VARCHAR(50) NOT NULL,
    [DESCRIPCION]     VARCHAR(250)  NULL    
    CONSTRAINT [PK_CATEGORIA_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_CATEGORIA_SERVICIO] ASC)   
);
