CREATE TABLE [dbo].[CLIENTE_PAGOS] (
    [ID_CLIENTEPAGO]  UNIQUEIDENTIFIER      NOT NULL,
    [ID_CLIENTE] CHAR (15) NULL,
    [FECHA]      DATETIME  NULL,
    [SUBTOTAL]   REAL      NULL,
    [DESCUENTO]  REAL      NULL,
    [TOTAL]      REAL      NULL,
    [ID_EMPRESA] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_CLIENTE_PAGO] PRIMARY KEY CLUSTERED ([ID_CLIENTEPAGO] ASC)
);

