CREATE TABLE [dbo].[EMPLEADOS_SERVICIOS] (
    [ID_EMPLEADO_SERVICIO] INT       IDENTITY (1, 1) NOT NULL,
    [ID_EMPLEADO]          CHAR (15) NULL,
    [ID_SERVICIO]          INT       NULL,
    CONSTRAINT [PK_EMPLEADOS_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_EMPLEADO_SERVICIO] ASC),
    CONSTRAINT [FK_ID_SERVICIO] FOREIGN KEY ([ID_SERVICIO]) REFERENCES [dbo].[SERVICIOS] ([ID_SERVICIO])
);

