CREATE TABLE [dbo].[EMPRESA_PROPIEDADES] (
    [ID_EMPRESA_PROPIEDAD]     UNIQUEIDENTIFIER NOT NULL,
	[ID_EMPRESA] UNIQUEIDENTIFIER NOT NULL,
	[ID_SISTEMA_PROPIEDAD] UNIQUEIDENTIFIER NOT NULL,
	[VALOR_PROPIEDAD] CHAR(15) NOT NULL,
	CONSTRAINT [PK_EMPRESA_PROPIEDADES] PRIMARY KEY ([ID_EMPRESA_PROPIEDAD] ASC),
	CONSTRAINT [FK_EMPRESA] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA]),
    CONSTRAINT [FK_SISTEMA_PROPIEDADES] FOREIGN KEY ([ID_SISTEMA_PROPIEDAD]) REFERENCES [dbo].[SISTEMA_PROPIEDADES] ([ID_SISTEMA_PROPIEDAD])
);