CREATE TABLE [dbo].[ENCUESTAS] (
    [ID_REGISTRO]        INT       IDENTITY (1, 1) NOT NULL,
    [ID_ENCUESTA]        INT       NULL,
    [ID_EMPLEADO]        CHAR (15) NULL,
    [ID_SERVICIO]        INT       NULL,
    [ASPECTO]            CHAR (10) NULL,
    [CRITERIO]           CHAR (12) NULL,
    [FECHA]              DATETIME  NULL,
    [PESO]               INT       NULL,
    [FECHA_REGISTRO]     DATETIME  NULL,
    [FECHA_MODIFICACION] DATETIME  NULL,
    CONSTRAINT [PK_ENCUESTAS] PRIMARY KEY CLUSTERED ([ID_REGISTRO] ASC)
);


GO

--Create insert trigger
CREATE TRIGGER [dbo].[MCS_MasterCreation] ON [dbo].[ENCUESTAS] FOR INSERT
AS
UPDATE [ENCUESTAS]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [ENCUESTAS].ID_REGISTRO = (SELECT TOP 1 ID_REGISTRO FROM INSERTED)


GO

--Create update trigger
CREATE TRIGGER [dbo].[MCS_MasterModification] ON [dbo].[ENCUESTAS] FOR UPDATE
AS
UPDATE [ENCUESTAS]
SET FECHA_MODIFICACION = current_timestamp
WHERE [ENCUESTAS].ID_REGISTRO = (SELECT TOP 1 ID_REGISTRO FROM INSERTED)

