CREATE TABLE [dbo].[LIQUIDACIONES] (
    [ID_REGISTRO]     INT       IDENTITY (1, 1) NOT NULL,
    [FECHA]           DATETIME  NULL,
    [ID_EMPLEADO]     CHAR (15) NULL,
    [TOTAL_SERVICIOS] REAL      NULL,
    [TOTAL_PRESTAMOS] REAL      NULL,
    [TOTAL_PAGADO]    REAL      NULL,
    CONSTRAINT [PK_LIQUIDACIONES] PRIMARY KEY CLUSTERED ([ID_REGISTRO] ASC)
);

