CREATE TABLE [dbo].[LIQUIDACIONES] (
    [ID_REGISTRO]     INT       IDENTITY (1, 1) NOT NULL,
    [FECHA]           DATETIME  NULL,
    [ID_EMPLEADO]     CHAR (15) NULL,
    [TOTAL_SERVICIOS] REAL      NULL,
    [TOTAL_PRESTAMOS] REAL      NULL,
    [TOTAL_PAGADO]    REAL      NULL,
    [ANIO]    INT      NOT NULL,
    [MES]    INT      NOT NULL,
    [QUINCENA]    INT      NOT NULL,
    [DIA]    SMALLDATETIME      NOT NULL,
    [ID_EMPRESA]     UNIQUEIDENTIFIER NOT NULL
    CONSTRAINT [PK_LIQUIDACIONES] PRIMARY KEY CLUSTERED ([ID_REGISTRO] ASC),
    CONSTRAINT [FK_ID_EMPRESA_LIQUIDACIONES] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA])
);

