CREATE TABLE [dbo].[MENU_USUARIOS](
	[ID_MENU_USUARIO] [uniqueidentifier] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[ID_MENU] [int] NOT NULL,
	[ESTADO] [bit] NOT NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_MENU_USUARIOS] PRIMARY KEY CLUSTERED 
(
	[ID_MENU_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO