CREATE TABLE [dbo].[MENU](
	[ID_MENU] [int] IDENTITY(1,1) NOT NULL,
	[RUTA_ACCESO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](30) NULL,
	[LOGO_BASE64] [nvarchar](max) NULL,
	[_PARENTID]	  [int] null,
	[_LEVEL]	  [int] null,
	[_CHILDREN]	  [int] null,
	[FECHA_REGISTRO] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
 CONSTRAINT [PK_MENU] PRIMARY KEY CLUSTERED 
(
	[ID_MENU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
