

CREATE TABLE [dbo].[MENU](
	[ID_MENU] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NULL,
	[RUTA_ACCESO] [varchar](50) NULL,
	[DESCRIPCION] [varchar](30) NULL,
	[LOGO_BASE64] [nvarchar](MAX) NULL,
	[FECHA_REGISTRO] [datetime] NULL,
	[FECHA_MODIFICACION] [datetime] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MENU]  WITH CHECK ADD  CONSTRAINT [FK_ID_USUARIO_MENU] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[USUARIOS] ([ID_USUARIO])
GO

ALTER TABLE [dbo].[MENU] CHECK CONSTRAINT [FK_ID_USUARIO_MENU]
GO

--Create insert trigger
CREATE TRIGGER [dbo].[MM_MasterCreation] on dbo.MENU FOR INSERT
AS
UPDATE MENU
SET FECHA_REGISTRO = GETDATE(),FECHA_MODIFICACION =  GETDATE()
WHERE MENU.ID_MENU = (SELECT Top 1 ID_MENU from INSERTED)

GO
--Create update trigger
CREATE TRIGGER [dbo].[MM_MasterModification] ON dbo.MENU FOR UPDATE
AS
UPDATE [MENU]
SET FECHA_MODIFICACION =  GETDATE()
WHERE [MENU].ID_MENU = (SELECT TOP 1 ID_MENU FROM INSERTED)