CREATE TABLE [dbo].[MUNICIPIOS] (
    [ID_MUNICIPIO] INT       IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       CHAR (30) NULL,
    CONSTRAINT [PK_MUNICIPIOS] PRIMARY KEY CLUSTERED ([ID_MUNICIPIO] ASC)
);

