CREATE TABLE [dbo].[MUNICIPIOS] (
    [ID_MUNICIPIO] INT       IDENTITY (1, 1) NOT NULL,
    [NOMBRE]       CHAR (60) NULL,
    [ID_DEPARTAMENTO] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_MUNICIPIOS] PRIMARY KEY CLUSTERED ([ID_MUNICIPIO] ASC),
    CONSTRAINT [FK_DEPARTAMENTOS] FOREIGN KEY ([ID_DEPARTAMENTO]) REFERENCES [dbo].[DEPARTAMENTOS] ([ID_DEPARTAMENTO])
);

