CREATE TABLE [dbo].[PRODUCTOS] (
    [ID_PRODUCTO]        INT              IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (25)        NULL,
    [DESCRIPCION]        CHAR (100)       NULL,
    [PRECIO]             REAL             NULL,
    [INVENTARIO]         INT              NULL,
    [FECHA_REGISTRO]     DATETIME         NULL,
    [FECHA_MODIFICACION] DATETIME         NULL,
    [ID_EMPRESA]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_PRODUCTOS] PRIMARY KEY CLUSTERED ([ID_PRODUCTO] ASC),
    CONSTRAINT [FK_ID_EMPRESA_PRODUCTO] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA])
);


GO
--Create insert trigger
CREATE TRIGGER [dbo].[MP_MasterCreation] ON dbo.PRODUCTOS FOR INSERT
AS
UPDATE [PRODUCTOS]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [PRODUCTOS].ID_PRODUCTO = (SELECT TOP 1 ID_PRODUCTO FROM INSERTED)

GO
--Create update trigger
CREATE TRIGGER [dbo].[MP_MasterModification] ON dbo.PRODUCTOS FOR UPDATE
AS
UPDATE [PRODUCTOS]
SET FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [PRODUCTOS].ID_PRODUCTO = (SELECT TOP 1 ID_PRODUCTO FROM INSERTED)
