CREATE TABLE [dbo].[PROMOCIONES](
	[ID_PROMOCION] [uniqueidentifier] NOT NULL,
	[ID_TIPO_PROMOCION] [uniqueidentifier] NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[VALOR] [decimal](18, 2) NOT NULL,
	[ESTADO] [char](10) NULL,
	[ID_EMPRESA] [uniqueidentifier] NOT NULL,
	[FECHA_CREACION] [datetime] NULL,
	[USUARIO_CREACION] [char](25) NULL,
	[FECHA_MODIFICACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [char](25) NULL,
	CONSTRAINT [FK_TIPO_PROMOCION] FOREIGN KEY ([ID_TIPO_PROMOCION]) REFERENCES [dbo].[TIPO_PROMOCIONES] ([ID_TIPO_PROMOCION]),
	CONSTRAINT [FK_EMPRESA_PROMOCIONES] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA]),
	CONSTRAINT [PK_PROMOCIONES] PRIMARY KEY CLUSTERED 
	(
		[ID_PROMOCION] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
