CREATE TABLE [dbo].[SERVICIOS] (
    [ID_SERVICIO]        INT              IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (30)        NULL,
    [DESCRIPCION]        CHAR (300)       NULL,      
    [ID_TIPOSERVICIO]    INT              NOT NULL,
    [ID_CATEGORIA_SERVICIO] UNIQUEIDENTIFIER NOT NULL,
    [FECHA_REGISTRO]     DATETIME   NULL,
    [FECHA_MODIFICACION] DATETIME   NULL,
    CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_SERVICIO] ASC),
    CONSTRAINT [FK_TIPO_SERVICIO] FOREIGN KEY ([ID_TIPOSERVICIO]) REFERENCES [dbo].[TIPO_SERVICIO] ([ID_TIPOSERVICIO]),
    CONSTRAINT [FK_CATEGORIA_SERVICIOS_SERVICIOS] FOREIGN KEY ([ID_CATEGORIA_SERVICIO]) REFERENCES [dbo].[CATEGORIA_SERVICIOS] ([ID_CATEGORIA_SERVICIO])
);

GO


