CREATE TABLE [dbo].[SERVICIOS] (
    [ID_SERVICIO]        INT              IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (30)        NULL,
    [DESCRIPCION]        CHAR (300)       NULL,
    [TIEMPO]             INT              NULL,
    [VALOR]              REAL             CONSTRAINT [DF_SERVICIOS_VALOR] DEFAULT ((0)) NULL,
    [ID_TIPOSERVICIO]    INT              NULL,
    [LOGO_BASE64]        NVARCHAR(MAX)    NULL,
    [ESTADO]             CHAR (10)        NULL,
    [ID_EMPRESA]         UNIQUEIDENTIFIER NOT NULL,
    [FECHA_REGISTRO]     DATETIME         NULL,
    [FECHA_MODIFICACION] DATETIME         NULL
    CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_SERVICIO] ASC),
    CONSTRAINT [FK_ID_EMPRESA_SERVICIO] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA]),
    CONSTRAINT [FK_TIPO_SERVICIO] FOREIGN KEY ([ID_TIPOSERVICIO]) REFERENCES [dbo].[TIPO_SERVICIO] ([ID_TIPOSERVICIO])
);

GO


