CREATE TABLE [dbo].[SERVICIOS] (
    [ID_SERVICIO]        INT              IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (30)        NULL,
    [DESCRIPCION]        CHAR (300)       NULL,
    [TIEMPO]             INT              NULL,
    [VALOR]              REAL             CONSTRAINT [DF_SERVICIOS_VALOR] DEFAULT ((0)) NULL,
    [ID_TIPOSERVICIO]    INT              NULL,
    [ESTADO]             CHAR (10)        NULL,
    [FECHA_REGISTRO]     DATETIME         NULL,
    [FECHA_MODIFICACION] DATETIME         NULL,
    [ID_EMPRESA]         UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_SERVICIOS] PRIMARY KEY CLUSTERED ([ID_SERVICIO] ASC),
    CONSTRAINT [FK_ID_EMPRESA_SERVICIO] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA]),
    CONSTRAINT [FK_TIPO_SERVICIO] FOREIGN KEY ([ID_TIPOSERVICIO]) REFERENCES [dbo].[TIPO_SERVICIO] ([ID_TIPOSERVICIO])
);


GO

--Create insert trigger
CREATE TRIGGER [dbo].[MS_MasterCreation] ON [dbo].[SERVICIOS] FOR INSERT
AS
UPDATE [SERVICIOS]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [SERVICIOS].ID_SERVICIO = (SELECT TOP 1 ID_SERVICIO FROM INSERTED)


GO

--Create update trigger
CREATE TRIGGER [dbo].[MS_MasterModification] ON [dbo].[SERVICIOS] FOR UPDATE
AS
UPDATE [SERVICIOS]
SET FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [SERVICIOS].ID_SERVICIO = (SELECT TOP 1 ID_SERVICIO FROM INSERTED)

