CREATE TABLE [dbo].[SISTEMA_PROPIEDADES] (
    [ID_SISTEMA_PROPIEDAD]     UNIQUEIDENTIFIER NOT NULL,
    [DESCRIPCION]              VARCHAR(100)  NOT NULL,
	[CODIGO]				   CHAR(5)  NOT NULL,
	[TIPO]					   CHAR(15) NOT NULL
	CONSTRAINT [PK_SISTEMA_PROPIEDADES] PRIMARY KEY ([ID_SISTEMA_PROPIEDAD] ASC)
);