CREATE TABLE [dbo].[TIPO_TRANSACCION] (
    [ID_TIPOTRANSACCION] INT        IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (10)  NULL,
    [DESCRIPCION]        CHAR (100) NULL,
    CONSTRAINT [PK_TIPO_TRANSACCION] PRIMARY KEY CLUSTERED ([ID_TIPOTRANSACCION] ASC)
);

