CREATE TABLE [dbo].[TIPO_SERVICIO] (
    [ID_TIPOSERVICIO]    INT        IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (30)  NULL,
    [DESCRIPCION]        CHAR (100) NULL,
    [FECHA_REGISTRO]     DATETIME   NULL,
    [FECHA_MODIFICACION] DATETIME   NULL,
    [ID_CATEGORIA_SERVICIO] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_TIPO_SERVICIO] PRIMARY KEY CLUSTERED ([ID_TIPOSERVICIO] ASC),
    CONSTRAINT [FK_CATEGORIA_SERVICIOS_TIPO_SERVICIOS] FOREIGN KEY ([ID_CATEGORIA_SERVICIO]) REFERENCES [dbo].[CATEGORIA_SERVICIOS] ([ID_CATEGORIA_SERVICIO])
);


GO

--Create insert trigger
CREATE TRIGGER [dbo].[MTS_MasterCreation] ON [dbo].[TIPO_SERVICIO] FOR INSERT
AS
UPDATE [TIPO_SERVICIO]
SET FECHA_REGISTRO = GETDATE(),FECHA_MODIFICACION = GETDATE()
WHERE [TIPO_SERVICIO].ID_TIPOSERVICIO = (SELECT TOP 1 ID_TIPOSERVICIO FROM INSERTED)


GO

--Create update trigger
CREATE TRIGGER [dbo].[MTS_MasterModification] ON [dbo].[TIPO_SERVICIO] FOR UPDATE
AS
UPDATE [TIPO_SERVICIO]
SET FECHA_MODIFICACION = GETDATE()
WHERE [TIPO_SERVICIO].ID_TIPOSERVICIO = (SELECT TOP 1 ID_TIPOSERVICIO FROM INSERTED)

