CREATE TABLE [dbo].[TIPO_PROMOCIONES](
	[ID_TIPO_PROMOCION] [uniqueidentifier] NOT NULL,
	[DESCRIPCION] [varchar](25) NULL,
 CONSTRAINT [PK_TIPO_PROMOCIONES] PRIMARY KEY CLUSTERED 
(
	[ID_TIPO_PROMOCION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

