CREATE TABLE [dbo].[TIPO_SERVICIO] (
    [ID_TIPOSERVICIO]    INT        IDENTITY (1, 1) NOT NULL,
    [NOMBRE]             CHAR (30)  NULL,
    [DESCRIPCION]        CHAR (100) NULL,
    [FECHA_REGISTRO]     DATETIME   NULL,
    [FECHA_MODIFICACION] DATETIME   NULL,
    CONSTRAINT [PK_TIPO_SERVICIO] PRIMARY KEY CLUSTERED ([ID_TIPOSERVICIO] ASC)
);


GO

--Create insert trigger
CREATE TRIGGER [dbo].[MTS_MasterCreation] ON [dbo].[TIPO_SERVICIO] FOR INSERT
AS
UPDATE [TIPO_SERVICIO]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [TIPO_SERVICIO].ID_TIPOSERVICIO = (SELECT TOP 1 ID_TIPOSERVICIO FROM INSERTED)


GO

--Create update trigger
CREATE TRIGGER [dbo].[MTS_MasterModification] ON [dbo].[TIPO_SERVICIO] FOR UPDATE
AS
UPDATE [TIPO_SERVICIO]
SET FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [TIPO_SERVICIO].ID_TIPOSERVICIO = (SELECT TOP 1 ID_TIPOSERVICIO FROM INSERTED)

