CREATE TABLE [dbo].[TRANSACCIONES] (
    [ID_TRANSACCION]     INT       IDENTITY (1, 1) NOT NULL,
    [FECHA]              DATETIME  NULL,
    [ID_PRODUCTO]        INT       NULL,
    [CANTIDAD]           INT       NULL,
    [ID_TIPOTRANSACCION] INT       NULL,
    [ID_EMP_CLI]         CHAR (15) NULL,
    [FECHA_REGISTRO]     DATETIME  NULL,
    [FECHA_MODIFICACION] DATETIME  NULL,
    CONSTRAINT [PK_TRANSACCIONES] PRIMARY KEY CLUSTERED ([ID_TRANSACCION] ASC),
    CONSTRAINT [FK_ID_TIPO_TRANSACCION] FOREIGN KEY ([ID_TIPOTRANSACCION]) REFERENCES [dbo].[TIPO_TRANSACCION] ([ID_TIPOTRANSACCION])
);


GO
--Create insert trigger
CREATE TRIGGER [dbo].[MT_MasterCreation] ON dbo.TRANSACCIONES FOR INSERT
AS
UPDATE [TRANSACCIONES]
SET FECHA_REGISTRO = CURRENT_TIMESTAMP,FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [TRANSACCIONES].ID_TRANSACCION = (SELECT TOP 1 ID_TRANSACCION FROM INSERTED)

GO
--Create update trigger
CREATE TRIGGER [dbo].[MT_MasterModification] ON dbo.TRANSACCIONES FOR UPDATE
AS
UPDATE [TRANSACCIONES]
SET FECHA_MODIFICACION = CURRENT_TIMESTAMP
WHERE [TRANSACCIONES].ID_TRANSACCION = (SELECT TOP 1 ID_TRANSACCION FROM INSERTED)
