CREATE TABLE [dbo].[TRANSACCIONES] (
    [ID_TRANSACCION]     INT       IDENTITY (1, 1) NOT NULL,
    [FECHA]              DATETIME  NULL,
    [ID_PRODUCTO]        INT       NULL,
    [CANTIDAD]           INT       NULL,
    [ID_TIPOTRANSACCION] INT       NULL,
    [ID_EMPLEADOCLIENTE] INT NULL,
    [ID_EMPRESA]         UNIQUEIDENTIFIER NOT NULL,
    [FECHA_REGISTRO]     DATETIME  NULL,
    [FECHA_MODIFICACION] DATETIME  NULL,
    CONSTRAINT [PK_TRANSACCIONES] PRIMARY KEY CLUSTERED ([ID_TRANSACCION] ASC),
    CONSTRAINT [FK_ID_TIPO_TRANSACCION] FOREIGN KEY ([ID_TIPOTRANSACCION]) REFERENCES [dbo].[TIPO_TRANSACCION] ([ID_TIPOTRANSACCION]),
    CONSTRAINT [FK_ID_EMPRESA_TRANSACCION] FOREIGN KEY ([ID_EMPRESA]) REFERENCES [dbo].[EMPRESA] ([ID_EMPRESA])
);

GO
