CREATE TABLE [dbo].[VISITAS] (
    [ID_VISITA]  INT       IDENTITY (1, 1) NOT NULL,
    [ID_CLIENTE] CHAR (15) NULL,
    [FECHA]      DATETIME  NULL,
    [SUBTOTAL]   REAL      NULL,
    [DESCUENTO]  REAL      NULL,
    [TOTAL]      REAL      NULL,
    CONSTRAINT [PK_VISITAS] PRIMARY KEY CLUSTERED ([ID_VISITA] ASC)
);

