-- TIPOS DE NOMINAS
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'MENSUAL','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'QUINCENAL','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'DIARIO','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'POR SERVICIOS','PAGO_PORCENTUAL')

--TIPOS DE TRANSACCION
INSERT INTO TIPO_TRANSACCION(NOMBRE,DESCRIPCION) VALUES('ENTRADA','ENTRADA DE PRODUCTO POR ACTUALIZACIÓN DEL INVENTARIO')
INSERT INTO TIPO_TRANSACCION(NOMBRE,DESCRIPCION) VALUES('VENTA','SALIDA DE PRODUCTO POR CONCEPTO DE VENTAS DEL PRODUCTO')
INSERT INTO TIPO_TRANSACCION(NOMBRE,DESCRIPCION) VALUES('INSUMO','SALIDA DE PRODUCTO POR CONCEPTO DE INSUMOS ENTREGADOS A LOS EMPLEADOS')