-- TIPOS DE NOMINAS
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'MENSUAL','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'QUINCENAL','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'DIARIO','PAGO_FIJO')
INSERT INTO TIPO_PAGO (ID_TIPOPAGO,DESCRIPCION,CRITERIO) VALUES (NEWID(),'POR SERVICIOS','PAGO_PORCENTUAL')