ALTER PROCEDURE ConsultarServicios(@IdEmpresa VARCHAR(36))
AS
BEGIN

	SELECT ID_SERVICIO, RTRIM(SERVICIOS.NOMBRE) AS NOMBRE,RTRIM(SERVICIOS.DESCRIPCION) AS DESCRIPCION,VALOR,TIEMPO,SERVICIOS.ID_TIPOSERVICIO,
	RTRIM(ESTADO) AS ESTADO,ID_EMPRESA,SERVICIOS.FECHA_REGISTRO,SERVICIOS.FECHA_MODIFICACION,RTRIM(TIPO_SERVICIO.NOMBRE) AS NOMBRE_TIPO_SERVICIO
	FROM SERVICIOS INNER JOIN TIPO_SERVICIO ON SERVICIOS.ID_TIPOSERVICIO = TIPO_SERVICIO.ID_TIPOSERVICIO WHERE ID_EMPRESA = @IdEmpresa

END

GO