CREATE PROCEDURE EliminarEmpleadoInsumo(@IdTransaccion INT, @Cantidad INT, @IdProducto INT)
AS

BEGIN	

	SET XACT_ABORT, NOCOUNT ON

	BEGIN TRY

		BEGIN TRANSACTION Tn_EliminarInsumo

		DELETE 
		FROM TRANSACCIONES 
		WHERE ID_TRANSACCION = @IdTransaccion

		UPDATE PRODUCTOS 
		SET INVENTARIO = INVENTARIO + @Cantidad
		WHERE ID_PRODUCTO = @IdProducto

		COMMIT TRANSACTION

	END TRY
	BEGIN CATCH

		IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION Tn_EliminarInsumo	
        DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE()
        RAISERROR (@ErrorMessage, 16, 1)	

	END CATCH

END

GO